### ISSUE TITLE
Fix Authentication

### ISSUE THREAD

**Issue by A-Guldborg** [AnalogIO/shifty-webapp#26]
Currently, authentication on Shifty does not match authentication in the app. In other words, the app converts the pincode before sending it to the backend server, where as Shifty does not alter any values. This means, using the same credentials for both pages does not currently work.

The goal is to enable using the same password for both places, however it is crucial to discuss security concerns for the log-in of Shifty that currently handles products with prices and user roles, but in the future might also handle Analog's finances. It might not be enough security to continue using a 4-digit pincode, at least for Shifty's usecase.

**Comment by marfavi** [comment]
For now, as a board member, I'd like to just have one separate user account (with no password constraints) for admin purposes.

I wouldn't mind restricting the Board member user role to accounts with secure passwords.

**Comment by A-Guldborg** [comment]
> For now, as a board member, I'd like to just have one separate user account (with no password constraints) for admin purposes.
> 
> I wouldn't mind restricting the Board member user role to accounts with secure passwords.

This should be easy, I suppose. Steps:
1. Open Swagger in production https://core.prd.analogio.dk/swagger/index.html#/
2. Use api/v1/Account/register to register an account with your preferred mail & password
3. Confirm the mail (Or manually confirm it directly in the database)
4. In the database directly, set the user role to Board

Voila, you have your first account with Board privileges. This can be an admin account with a randomly generated password stored in BitWarden. I suggest tho, that the whole board does not share the same account and uses the same admin account for privileged endpoints in order to avoid cases where we do not know who made what changes (i.e. nobody knows why user X is suddenly "Manager" because the sysadmin account changed the role). (I don't know how much logging we are doing in the backend currently, but this might also need to be prioritized)
